<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdrTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('adr')->insert([
            [
                'adrtext' => '01/00',
                'title' => 'Reversing Lamps',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '02/01',
                'title' => 'Side Door Latches and Hinges',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '03/04',
                'title' => 'Seats and Seat Anchorages',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '03/04',
                'title' => 'Seats and Seat Anchorages',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '04/06',
                'title' => 'Seatbelts',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '04/06',
                'title' => 'Seatbelts',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '04/06',
                'title' => 'Seatbelts',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '05/06',
                'title' => 'Anchorages for Seatbelts',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '05/06',
                'title' => 'Anchorages for Seatbelts',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '05/06',
                'title' => 'Anchorages for Seatbelts',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '06/00',
                'title' => 'Direction Indicators',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '06/00',
                'title' => 'Direction Indicators',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '06/00',
                'title' => 'Direction Indicators',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '08/01',
                'title' => 'Safety Glazing Materials',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '10/02',
                'title' => 'Steering Column',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '11/00',
                'title' => 'Internal Sun Visors',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '13/00',
                'title' => 'Installation of Lighting and Light-Signalling Devices on other than L-group Vehicles',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '14/02',
                'title' => 'Rear Vision Mirrors',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '14/02',
                'title' => 'Rear Vision Mirrors',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '18/03',
                'title' => 'Instrumentation',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '21/00',
                'title' => 'Instrument Panel',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '21/00',
                'title' => 'Instrument Panel',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '22/00',
                'title' => 'Head Restraints',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '23/03',
                'title' => 'Passenger Car Tyres',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '23/03',
                'title' => 'Passenger Car Tyres',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '25/02',
                'title' => 'Anti-Theft Lock',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '29/00',
                'title' => 'Side Door Strength',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '30/01',
                'title' => 'Smoke Emission Control for Diesel Vehicles',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '31/04',
                'title' => 'Brake Systems for Passenger Cars',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '31/04',
                'title' => 'Brake Systems for Passenger Cars',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '31/04',
                'title' => 'Brake Systems for Passenger Cars',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '34/03',
                'title' => 'Child Restraint Anchorages and Child Restraint Anchor Fittings',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '42/05',
                'title' => 'General Safety Requirements',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '43/04',
                'title' => 'Vehicle Configuration & Dimensions',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '44/02',
                'title' => 'Specific Vehicle Requirements',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '45/01',
                'title' => 'Lighting & Light Signalling Devices not Covered by ECE Regulations',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '46/00',
                'title' => 'Headlamps',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '46/00',
                'title' => 'Headlamps',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '47/00',
                'title' => 'Retroreflectors',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '48/00',
                'title' => 'Devices for Illumination of Rear Registration Plates',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '49/00',
                'title' => 'Front and Rear Position (Side) Lamps, Stop Lamps and End-Outline Marker Lamps',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '49/00',
                'title' => 'Front and Rear Position (Side) Lamps, Stop Lamps and End-Outline Marker Lamps',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '49/00',
                'title' => 'Front and Rear Position (Side) Lamps, Stop Lamps and End-Outline Marker Lamps',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '50/00',
                'title' => 'Front Fog Lamps',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '51/00',
                'title' => 'Filament Lamps',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '52/00',
                'title' => 'Rear Fog Lamps',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '60/00',
                'title' => 'Centre High Mounted Stop Lamp',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '61/03',
                'title' => 'Vehicle Marking',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '62/02',
                'title' => 'Mechanical Connections Between Vehicles',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '69/00',
                'title' => 'Full Frontal Impact Occupant Protection',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '72/00',
                'title' => 'Dynamic Side Impact Occupant Protection',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '73/00',
                'title' => 'Offset Frontal Impact Occupant Protection',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '74/00',
                'title' => 'Side Marker Lamps',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '75/00',
                'title' => 'Headlamp Cleaners',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '76/00',
                'title' => 'Daytime Running Lamps',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '77/00',
                'title' => 'Gas Discharge Headlamps ',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '78/00',
                'title' => 'Gas Discharge Light Sources',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '79/04',
                'title' => 'Emission Control for Light Vehicles',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '81/02',
                'title' => 'Fuel Consumption Labelling for Light Vehicles',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '82/00',
                'title' => 'Engine Immobilisers',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '83/00',
                'title' => 'External Noise',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '85/00',
                'title' => 'Pole Side Impact Performance',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '86/00',
                'title' => 'Parking Lamps',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '87/00',
                'title' => 'Cornering Lamps',
                'compliancetext' => 'Exemption',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '88/00',
                'title' => 'Electronic Stability Control',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '89/00',
                'title' => 'Brake Assist System',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '90/00',
                'title' => 'Steering System',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '92/00',
                'title' => 'External Projections',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '93/00',
                'title' => 'Forward Field of View',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '94/00',
                'title' => 'Audible Warning',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adrtext' => '95/00',
                'title' => 'Installation of Tyres',
                'compliancetext' => 'Full',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
